// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpyCz8GW1fF4Yd39cpXn3n6Whysm2tgCU',
    appId: '1:726965641835:web:7fecf94c2c9d18cf12872e',
    messagingSenderId: '726965641835',
    projectId: 'c0fee-a18c8',
    authDomain: 'c0fee-a18c8.firebaseapp.com',
    storageBucket: 'c0fee-a18c8.appspot.com',
    measurementId: 'G-VM257H0WGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4QWPuCQPhKb1H4kzatUF3alLVC3Z6Kg',
    appId: '1:726965641835:android:8366f503ef456da212872e',
    messagingSenderId: '726965641835',
    projectId: 'c0fee-a18c8',
    storageBucket: 'c0fee-a18c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8w5rj1ME-qDKkHLHzcd34LUuMyA7wgvc',
    appId: '1:726965641835:ios:9b0d4c06f42d84c512872e',
    messagingSenderId: '726965641835',
    projectId: 'c0fee-a18c8',
    storageBucket: 'c0fee-a18c8.appspot.com',
    iosClientId: '726965641835-mhu7rqf0psffa5u1vdu0cef12ckqb1g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.c0feeMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8w5rj1ME-qDKkHLHzcd34LUuMyA7wgvc',
    appId: '1:726965641835:ios:9b0d4c06f42d84c512872e',
    messagingSenderId: '726965641835',
    projectId: 'c0fee-a18c8',
    storageBucket: 'c0fee-a18c8.appspot.com',
    iosClientId: '726965641835-mhu7rqf0psffa5u1vdu0cef12ckqb1g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.c0feeMobileApp',
  );
}
